config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { in: (5..16)}, uniqueness: true
  validates :password, presence: true, length: { in: (5..16)}
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    
  end
  def create
    user  = User.find_by_username(params[:username])
    if user && user.authenticate_password
      session[:user_id] = user.id
      redirect_to root_path,
      notice: 'You have succesfully signed in'
    else 
      render 'new',
      alert: "Username or Password Incorrect"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
   end
  private 
  def authenticate_password
    true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path,
    notice: " , You Have Successfully Registered as "
    else
      render 'new',
      alert:  'Registration Unsuccessful Something went wrong, Please Try Again'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeneralApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = 'container-fluid'>
      <p class="is-success row">
        <% if notice %>
          <%= notice %>
        <% end %>
      </p>

      <p class="is-danger row">
        <% if alert %>
          <%= alert %>
        <% end %>
      </p>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <%= link_to root_path class: "navbar-brand" do %>
            <h3>Instagram</h3>
          <% end %>
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to 'Home', root_path, class: "nav-link active"%>
              </li>          
             
             <% if current_user %>
                <li class="nav-item">
                  <%= link_to current_user.name , root_path, class: "nav-link active"%>
                </li>

                 <li class="nav-item">
                  <%= link_to 'sign out',  session_path('active'), method: :delete, class: "nav-link active"%>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'sign in', new_session_path, class: "nav-link active"%>
                </li>
                <li class="nav-item">
                  <%= link_to 'sign up', new_user_path, class: "nav-link active"%>
                </li>
             <% end %>      
                       
              
              
            </ul>
          </div>
        </div>
      </nav>
      <%= yield %>
      <footer class = 'container'>
        <ul class = 'row justify-content-center text-center'>
          <%= link_to class: ''  do %>
            <li>About</li>
          <% end %>
          <%= link_to class: ''  do %>
            <li>Blog</li>
          <% end %>
          <%= link_to class: ''  do %>
            <li>Jobs</li>
          <% end %>
          <%= link_to class: ''  do %>
            <li>Help</li>
          <% end %>
          <%= link_to class: ''  do %>
            <li>API</li>
          <% end %>
          <%= link_to class: ''  do %>
            <li>Privacy</li>
          <% end %>
          <%= link_to class: ''  do %>
            <li>Terms</li>
          <% end %>
          <%= link_to class: ''  do %>
            <li>Top Accounts</li>
          <% end %>
          <%= link_to class: ''  do %>
            <li>Hashtags</li>
          <% end %>
          <%= link_to class: ''  do %>
            <li>Locations</li>
          <% end %> 
        </ul>
        <div class="row justify-content-center">
          <span>English</span> <span>2021 Instagram from Facebook</span>
        </div>
      </footer>
  </body>
</html>

app/views/users/_user.html.erb
<p>user.name</p>

app/views/users/index.html.erb
<div class="row">
  <div class="col">
    <h2>Feeds</h2>
  </div>
  <div class="col">
    <h1>Welcome to Instagram</h1>
    <%= render @users %>
  </div>

</div>

app/views/users/new.html.erb
  <div class="container w-50 ">
    <section>
      <h2>Instagram</h2>
      <h5>Sign up to see photos and videos of your friends.</h5>
      <div>
        <button class = 'btn bg-info w-100'>
          <span>icon</span>
          <span>Log in with facebook</span>
        </button>
      </div>
    </section>

    <section class=" ">

      <%= form_for @user do |f| %>
        <%= f.label :name, 'Name',class: "form-label" %>
        <%= f.text_field :name, class: "form-control mb-3"%>
        
        <%  @user.errors.full_messages_for(:name).each do |message| %>
          <div>
            <p><%= message %></p>
          </div>
        <% end %>
        

        <%= f.label :username, 'User Name',class: "form-label" %>
        <%= f.text_field :username, class: "form-control mb-1"%>

        <%= f.label :email, 'Email',class: "form-label" %>
        <%= f.email_field :email, class: "form-control mb-1"%>

        <%= f.label :password, 'Password',class: "form-label" %>
        <%= f.password_field :password, class: "form-control mb-1"%>
      
        <%= f.submit 'Sign up', class: "btn form-control btn-info" %> 
      <% end %>
    </section>
    <section class="text-center">
      <p>By signing up, you agree to out <span>Terms</span>, <span>Data</span> <span>Policy and <span>Cookies Policy</span></span>
      </p>
    </section>
 
    <div class="text-center">
      <p>Have an account? 
        <span><%= link_to 'Log in', new_session_path %></span>
      </p>
    </div>
    <p class = 'text-center' >Get the App</p>
    <section class="text-center">
        <button class = 'btn bg-info '></button>
        <button class = 'btn bg-info'></button>
    </section>
  </div>

  
  